# Generated by Django 4.1.2 on 2022-10-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True)),
                ('password_hash', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=3)),
                ('session', models.CharField(max_length=200)),
                ('salt', models.CharField(max_length=200)),
                ('description', models.TextField(default='Cristiano Ronaldo: SIII-III-III', max_length=500)),
            ],
        ),
    ]
